server.port: 8081

app:
    name: My App
    description: Welcome to the ${app.name}

my:
   greeting: Hello World
   list:
     values: foo,doo,poo

db:
   connection: "{connectionString: 'www.google.com', userName: 'foo', password: 'pass'}"
   host: 127.0.0.1
   port: 1200

management.endpoints.web.exposure.include: "*"

spring:  profiles:    active: test